export const XP = {
  COMPLETE_WORKOUT: 50,
  LOG_SET: 5,
  HIT_PERSONAL_RECORD: 100,

  CREATE_PROJECT: 30,
  LOG_CODING_SESSION: 25,
  CODING_SESSION_PER_10_MIN: 5,
  NIGHT_OWL_BONUS: 10,
  COMPLETE_MILESTONE: 80,
  SHIP_PROJECT: 150,

  DSA_EASY: 20,
  DSA_MEDIUM: 40,
  DSA_HARD: 80,

  LEARNING_COURSE: 200,
  LEARNING_BOOK: 150,
  LEARNING_TUTORIAL: 50,
  LEARNING_VIDEO: 30,
  LEARNING_DOCUMENTATION: 20,
  LEARNING_PAPER: 40,

  LOG_WEIGHT: 15,
  HIT_WEIGHT_GOAL: 200,

  LOG_MEAL: 10,
  LOG_SLEEP_GOOD: 15,
  LOG_SLEEP_SHORT: 5,
  COMPLETE_HABIT: 10,
  HABIT_BUNDLE_BONUS: 50,
  COMPLETE_FAST_BASE: 50,
  COMPLETE_FAST_PER_HOUR: 5,
  HIT_STEP_GOAL: 20,
  HIT_SPIRIT_GOAL: 200,

  LOG_TRANSACTION: 10,
  STAY_UNDER_BUDGET: 40,
  HIT_SAVINGS_GOAL: 120,

  COMPLETE_TASK_C: 20,
  COMPLETE_TASK_B: 30,
  COMPLETE_TASK_A: 50,
  COMPLETE_TASK_S: 80,
  COMPLETE_ALL_DAILY_TASKS: 75,
} as const;

export const streakMultiplier = (days: number) =>
  Math.min(1 + Math.floor(days / 7) * 0.25, 3);

export const xpForTaskPriority = (priority: 'S' | 'A' | 'B' | 'C') => ({
  S: XP.COMPLETE_TASK_S,
  A: XP.COMPLETE_TASK_A,
  B: XP.COMPLETE_TASK_B,
  C: XP.COMPLETE_TASK_C,
}[priority]);
